### ISSUE TITLE
can not capture the console operation on edit role->policy in json form.

### ISSUE THREAD

**Issue by testuser1ab** [iann0036/AWSConsoleRecorder#50]
**Describe the bug**

When I was operation in console IAM->Roles->Summary->Policy name -> Edit policy and edit the json then save the policy json.

Console Recorder for AWS only gives me
import boto3

iam_client = boto3.client('iam', region_name='xxx')

response = iam_client.list_policies()

Key operation was missing

https://console.aws.amazon.com/iam/home?#/roles/rolename$jsonEditor?policyName=policyname&section=permissions&step=edit

**Related Mapping**
If applicable to a specific type, e.g. ec2.DescribeInstances

**Related Language**
If applicable to a specific language output, e.g. JavaScript

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by iann0036** [comment]
Available in 0.3.34 per the above commit.

Note that due to the current health crisis, extension reviewers indicate there may be significant delays (weeks) before getting current versions published. You may wish to install locally if you intend to use this functionality before then.

Feel free to re-open if you see any issues.
