### ISSUE TITLE
Dynamodb Query and Update not recorded

### ISSUE THREAD

**Issue by testuser1ab** [iann0036/AWSConsoleRecorder#51]
When I am operating dynamodb though aws console, and Recording by AWSConsoleRecoder  .

The query operation and update operation is not recorded

**Comment by iann0036** [comment]
Added in d98295d06203137623df2ee5e800d0c6dd3edd43.

I didn't test extensively with all kinds of values, but it should work in theory.

Note that due to the current health crisis, extension reviewers indicate there may be significant delays (weeks) before getting current versions published. You may wish to install locally if you intend to use this functionality before then.

Feel free to re-open if you see any issues.
